# Generated by Django 6.0.4 on 2026-06-05 06:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gl_code', models.CharField(max_length=20, unique=True)),
                ('product', models.CharField(choices=[('ATM', 'ATM'), ('POS', 'POS'), ('ECOM', 'ECOM'), ('IMPS', 'IMPS')], max_length=10)),
                ('gl_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Fee'), ('GST', 'GST'), ('NPCI', 'NPCI Switching Fee'), ('NPCI_GST', 'NPCI Switching Fee GST'), ('SETTLEMENT', 'Settlement')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('ATM', 'ATM'), ('POS', 'POS'), ('ECOM', 'ECOM'), ('IMPS', 'IMPS')], max_length=10)),
                ('gl_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Fee'), ('GST', 'GST'), ('NPCI', 'NPCI Switching Fee'), ('NPCI_GST', 'NPCI Switching Fee GST'), ('SETTLEMENT', 'Settlement')], max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GLPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('ATM', 'ATM'), ('POS', 'POS'), ('ECOM', 'ECOM'), ('IMPS', 'IMPS')], max_length=10)),
                ('approved_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approved_fee_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('switching_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('switching_fee_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('posted', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('date', 'product')},
            },
        ),
        migrations.CreateModel(
            name='GLDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debit_during_the_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_during_the_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_recon.glaccount')),
            ],
            options={
                'unique_together': {('gl_account', 'balance_date')},
            },
        ),
    ]
