# Generated by Django 6.0.4 on 2026-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gldailybalance',
            name='gl_account',
            field=models.CharField(max_length=100),
        ),
    ]
