# Generated by Django 6.0.4 on 2026-06-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_recon', '0002_alter_gldailybalance_gl_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='glaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GLOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_recon.glaccount')),
            ],
            options={
                'unique_together': {('gl_account', 'opening_date')},
            },
        ),
    ]
