# Generated by Django 6.0.4 on 2026-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_recon', '0003_glaccount_is_active_glopeningbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldailybalance',
            name='txn_type',
            field=models.CharField(choices=[('ACQUIRER', 'Acquirer'), ('ISSUER', 'Issuer')], default='ACQUIRER', max_length=20),
            preserve_default=False,
        ),
    ]
