# Generated by Django 6.0.4 on 2026-06-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_recon', '0004_gldailybalance_txn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gldailybalance',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl_recon.glaccount'),
        ),
    ]
