# Generated by Django 6.0.4 on 2026-06-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_recon', '0005_alter_gldailybalance_gl_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gldailybalance',
            unique_together={('gl_account', 'balance_date', 'txn_type')},
        ),
    ]
