"""
Database migration file generated by Django to keep the database schema in sync with model changes.

Professional note:
    This project follows a simple separation of concerns:
    models store data, forms validate input, views control request/response flow,
    and services contain business rules such as import, reconciliation, dashboard
    summaries, dispute creation, and Excel generation.
"""

# Generated by Django 6.0.4 on 2026-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NDPGUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField()),
                ('total_records', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_1_acquirer_filename', models.CharField(max_length=255)),
                ('cycle_1_issuer_filename', models.CharField(max_length=255)),
                ('cycle_2_acquirer_filename', models.CharField(max_length=255)),
                ('cycle_2_issuer_filename', models.CharField(max_length=255)),
                ('cycle_3_acquirer_filename', models.CharField(max_length=255)),
                ('cycle_3_issuer_filename', models.CharField(max_length=255)),
                ('cycle_4_acquirer_filename', models.CharField(max_length=255)),
                ('cycle_4_issuer_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RGCSUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField()),
                ('record_nature', models.CharField(choices=[('ISSUER', 'Issuer'), ('ACQUIRER', 'Acquirer')], default='ISSUER', max_length=20)),
                ('file_861', models.CharField(blank=True, max_length=255, null=True)),
                ('file_862', models.CharField(blank=True, max_length=255, null=True)),
                ('file_863', models.CharField(blank=True, max_length=255, null=True)),
                ('file_864', models.CharField(blank=True, max_length=255, null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NDPGIMPSRawUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('ACQUIRER', 'Acquirer'), ('ISSUER', 'Issuer')], db_index=True, max_length=20)),
                ('file_date', models.DateField(db_index=True)),
                ('cycle_no', models.PositiveIntegerField(db_index=True)),
                ('raw_header', models.CharField(max_length=100)),
                ('source_filename', models.CharField(max_length=255)),
                ('eof_record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='FAILED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('file_type', 'file_date', 'cycle_no', 'source_filename')},
            },
        ),
        migrations.CreateModel(
            name='NDPGATMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('ACQUIRER', 'Acquirer'), ('ISSUER', 'Issuer')], max_length=10)),
                ('cycle_no', models.CharField(choices=[('1', 'Cycle 1'), ('2', 'Cycle 2'), ('3', 'Cycle 3'), ('4', 'Cycle 4')], max_length=1)),
                ('participant_id', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(max_length=2)),
                ('from_account_type', models.CharField(max_length=2)),
                ('to_account_type', models.CharField(max_length=2)),
                ('transaction_serial_number', models.CharField(max_length=12)),
                ('response_code', models.CharField(max_length=2)),
                ('pan_number', models.CharField(max_length=16)),
                ('member_number', models.CharField(max_length=6)),
                ('approval_number', models.CharField(max_length=6)),
                ('stan_no', models.CharField(max_length=6)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.CharField(max_length=6)),
                ('merchant_category_code', models.CharField(max_length=4)),
                ('card_acceptor_settlement_date', models.CharField(max_length=6)),
                ('card_acceptor_id', models.CharField(max_length=15)),
                ('card_acceptor_terminal_id', models.CharField(max_length=8)),
                ('card_acceptor_terminal_location', models.CharField(max_length=36)),
                ('acquirer_id', models.CharField(max_length=15)),
                ('acquirer_settlement_date', models.CharField(blank=True, max_length=6, null=True)),
                ('network_id', models.CharField(blank=True, max_length=3, null=True)),
                ('account_1_number', models.CharField(blank=True, max_length=16, null=True)),
                ('account_1_branch_id', models.CharField(blank=True, max_length=13, null=True)),
                ('account_2_number', models.CharField(blank=True, max_length=16, null=True)),
                ('account_2_branch_id', models.CharField(blank=True, max_length=13, null=True)),
                ('transaction_currency_code', models.CharField(max_length=3)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_activity_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('raw_record', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ndpg.ndpguploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NDPGIMPSRawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('from_account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('to_account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_serial_number', models.CharField(db_index=True, max_length=30)),
                ('response_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('approval_no', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('merchant_category_code', models.CharField(blank=True, max_length=10, null=True)),
                ('card_acceptor_settlement_date', models.DateField(blank=True, db_index=True, null=True)),
                ('card_acceptor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('acquirer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('bene_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bene_account_no', models.CharField(blank=True, max_length=40, null=True)),
                ('rem_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('remitter_account_no', models.CharField(blank=True, max_length=40, null=True)),
                ('file_type', models.CharField(choices=[('ACQUIRER', 'Acquirer'), ('ISSUER', 'Issuer')], db_index=True, max_length=20)),
                ('file_date', models.DateField(db_index=True)),
                ('cycle_no', models.PositiveIntegerField(db_index=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('raw_header', models.CharField(blank=True, max_length=100, null=True)),
                ('eof_record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ndpg.ndpgimpsrawuploadbatch')),
            ],
            options={
                'unique_together': {('transaction_serial_number', 'actual_transaction_amount', 'file_type', 'cycle_no', 'file_date')},
            },
        ),
        migrations.CreateModel(
            name='RGCSRawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_nature', models.CharField(choices=[('ISSUER', 'Issuer'), ('ACQUIRER', 'Acquirer')], default='ISSUER', max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=2)),
                ('product_id', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(max_length=2)),
                ('from_account_type', models.CharField(blank=True, max_length=2, null=True)),
                ('to_account_type', models.CharField(blank=True, max_length=2, null=True)),
                ('action_code', models.CharField(max_length=1)),
                ('response_code', models.CharField(max_length=2)),
                ('pan_number', models.CharField(max_length=19)),
                ('approval_number', models.CharField(blank=True, max_length=6, null=True)),
                ('rrn', models.CharField(max_length=12)),
                ('stan_no', models.CharField(blank=True, max_length=6, null=True)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('transaction_datetime', models.DateTimeField()),
                ('merchant_category_code', models.CharField(blank=True, max_length=4, null=True)),
                ('card_acceptor_id', models.CharField(blank=True, max_length=15, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=8, null=True)),
                ('terminal_location', models.CharField(blank=True, max_length=40, null=True)),
                ('acquirer_id', models.CharField(blank=True, max_length=11, null=True)),
                ('transaction_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('card_holder_billing_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('card_holder_billing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_txn_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('actual_txn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ndpg.rgcsuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['record_nature', 'transaction_date'], name='ndpg_rgcsra_record__4e96f8_idx'), models.Index(fields=['rrn'], name='ndpg_rgcsra_rrn_774d99_idx'), models.Index(fields=['stan_no'], name='ndpg_rgcsra_stan_no_f17692_idx'), models.Index(fields=['source_filename'], name='ndpg_rgcsra_source__c0d97d_idx')],
            },
        ),
    ]
