# Generated by Django 6.0.4 on 2026-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndpgatmtransaction',
            name='card_acceptor_settlement_date',
            field=models.DateField(),
        ),
    ]
