# Generated by Django 6.0.4 on 2026-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndpg', '0002_alter_ndpgatmtransaction_card_acceptor_settlement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndpgatmtransaction',
            name='acquirer_settlement_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
