# Generated by Django 6.0.4 on 2026-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndpg', '0003_alter_ndpgatmtransaction_acquirer_settlement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndpgatmtransaction',
            name='acquirer_settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
