# Generated by Django 6.0.4 on 2026-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('stan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rrn', models.CharField(blank=True, max_length=30, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('case_status', models.CharField(default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMPSDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_serial_number', models.CharField(db_index=True, max_length=50)),
                ('rrn', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(db_index=True, max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('case_status', models.CharField(db_index=True, default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'transaction_serial_number'],
                'unique_together': {('transaction_date', 'transaction_serial_number', 'source_status')},
            },
        ),
        migrations.CreateModel(
            name='RGCSDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('rrn', models.CharField(db_index=True, max_length=30)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(db_index=True, max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('case_status', models.CharField(db_index=True, default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'rrn'],
                'unique_together': {('transaction_date', 'rrn', 'source_status')},
            },
        ),
    ]
