"""
Database migration file generated by Django to keep the database schema in sync with model changes.

Professional note:
    This project follows a simple separation of concerns:
    models store data, forms validate input, views control request/response flow,
    and services contain business rules such as import, reconciliation, dashboard
    summaries, dispute creation, and Excel generation.
"""

# Generated by Django 6.0.4 on 2026-05-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('stan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rrn', models.CharField(blank=True, max_length=30, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('case_status', models.CharField(default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
