"""
Database migration file generated by Django to keep the database schema in sync with model changes.

Professional note:
    This project follows a simple separation of concerns:
    models store data, forms validate input, views control request/response flow,
    and services contain business rules such as import, reconciliation, dashboard
    summaries, dispute creation, and Excel generation.
"""

# Generated manually for RGCS and IMPS dispute cases

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGCSDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('rrn', models.CharField(db_index=True, max_length=30)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(db_index=True, max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('case_status', models.CharField(db_index=True, default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'rrn'],
                'unique_together': {('transaction_date', 'rrn', 'source_status')},
            },
        ),
        migrations.CreateModel(
            name='IMPSDisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_serial_number', models.CharField(db_index=True, max_length=50)),
                ('rrn', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('source_status', models.CharField(db_index=True, max_length=50)),
                ('dispute_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('case_status', models.CharField(db_index=True, default='OPEN', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'transaction_serial_number'],
                'unique_together': {('transaction_date', 'transaction_serial_number', 'source_status')},
            },
        ),
    ]
