# Generated by Django 6.0.4 on 2026-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdisputecase',
            name='dispute_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
