"""
Database migration file generated by Django to keep the database schema in sync with model changes.

Professional note:
    This project follows a simple separation of concerns:
    models store data, forms validate input, views control request/response flow,
    and services contain business rules such as import, reconciliation, dashboard
    summaries, dispute creation, and Excel generation.
"""

# Generated by Django 6.0.4 on 2026-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbs', '0001_initial'),
        ('ndpg', '0001_initial'),
        ('switchlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMPSReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_serial_number', models.CharField(db_index=True, max_length=50)),
                ('rrn', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cbs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('switch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ndpg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('MATCHED_ALL', 'Matched in CBS, Switch and NDPG'), ('CBS_ONLY', 'CBS Only'), ('SWITCH_ONLY', 'Switch Only'), ('NDPG_ONLY', 'NDPG Only'), ('CBS_SWITCH_ONLY', 'CBS and Switch Only'), ('CBS_NDPG_ONLY', 'CBS and NDPG Only'), ('SWITCH_NDPG_ONLY', 'Switch and NDPG Only'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('FAILED_NDPG_ONLY', 'Failed NDPG Only'), ('CBS_AUTO_REVERSED', 'CBS Auto Reversed')], db_index=True, max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('cbs_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imps_reconciliation_results', to='cbs.cbsimpstransaction')),
                ('ndpg_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imps_reconciliation_results', to='ndpg.ndpgimpsrawtransaction')),
                ('switch_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imps_reconciliation_results', to='switchlog.switchimpstransaction')),
            ],
            options={
                'unique_together': {('transaction_date', 'transaction_serial_number', 'status')},
            },
        ),
    ]
