# Generated by Django 6.0.4 on 2026-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsatmtransaction',
            name='settlement_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
