# Generated by Django 6.0.4 on 2026-05-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbsatmtransaction',
            name='account_type',
            field=models.CharField(default='10', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cbsatmtransaction',
            name='rrn_no',
            field=models.CharField(default='000000000000', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cbsatmtransaction',
            name='acquirer_gl',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cbsatmtransaction',
            name='card_no',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='cbsatmtransaction',
            name='customer_account_no',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
