# Generated by Django 6.0.4 on 2026-05-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0002_cbsatmtransaction_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgcsuploadbatch',
            name='source_filename',
            field=models.CharField(max_length=255),
        ),
    ]
