"""
Database migration file generated by Django to keep the database schema in sync with model changes.

Professional note:
    This project follows a simple separation of concerns:
    models store data, forms validate input, views control request/response flow,
    and services contain business rules such as import, reconciliation, dashboard
    summaries, dispute creation, and Excel generation.
"""

# Generated by Django 6.0.4 on 2026-05-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rrn', models.CharField(blank=True, max_length=30, null=True)),
                ('cbs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ndpg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('switch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cbs_present', models.BooleanField(default=False)),
                ('ndpg_present', models.BooleanField(default=False)),
                ('switch_present', models.BooleanField(default=False)),
                ('matched_by', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('MATCHED_ALL', 'Matched in All Sources'), ('CBS_ONLY', 'CBS Only'), ('NDPG_ONLY', 'NDPG Only'), ('SWITCH_ONLY', 'Switch Only'), ('CBS_NDPG_ONLY', 'CBS and NDPG Only'), ('CBS_SWITCH_ONLY', 'CBS and Switch Only'), ('NDPG_SWITCH_ONLY', 'NDPG and Switch Only'), ('CBS_AUTO_REVERSED', 'CBS Auto Reversed'), ('SWITCH_WITHDRAWAL_REVERSED', 'Switch Withdrawal Reversed'), ('FAILED_REVERSED_NO_DISPUTE', 'Failed / Reversed - No Dispute'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('FAILED_NDPG_ONLY', 'Failed Txns NDPG Only'), ('NDPG_SWITCH_ONLY_0_AMOUNT', 'NDPG Switch Only Zero Amount'), ('SWITCH_ONLY_DECLINED', 'Switch Only Declined'), ('MATCHED_ONUS', 'Matched On-Us'), ('PENDING_NDPG_NEXT_DAY', 'Pending NDPG Next Day Settlement'), ('AUTO_MATCHED_NEXT_DAY_NDPG', 'Auto Matched with Next Day NDPG')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
