# Generated by Django 6.0.4 on 2026-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RGCSReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('rrn', models.CharField(max_length=30)),
                ('cbs_transaction_id', models.IntegerField(blank=True, null=True)),
                ('ndpg_transaction_id', models.IntegerField(blank=True, null=True)),
                ('switch_transaction_id', models.IntegerField(blank=True, null=True)),
                ('cbs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ndpg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('switch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('CBS_ONLY', 'CBS Only'), ('NDPG_ONLY', 'NDPG Only'), ('SWITCH_ONLY', 'Switch Only'), ('CBS_NDPG_ONLY', 'CBS + NDPG Only'), ('CBS_SWITCH_ONLY', 'CBS + Switch Only'), ('NDPG_SWITCH_ONLY', 'NDPG + Switch Only'), ('AMOUNT_MISMATCH', 'Amount Mismatch')], max_length=40)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'rrn'],
                'unique_together': {('transaction_date', 'rrn')},
            },
        ),
    ]
