# Generated by Django 6.0.4 on 2026-05-29 11:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMSettlementCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('cycle_no', models.CharField(max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='atm_settlement/')),
                ('issuer_sub_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('acquirer_sub_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('settlement_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('net_adjusted_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('final_settlement_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('settlement_date', 'cycle_no')},
            },
        ),
        migrations.CreateModel(
            name='ATMSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('txn_count', models.IntegerField(default=0)),
                ('debit_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('settlement_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='atm_settlement.atmsettlementcycle')),
            ],
        ),
    ]
